general:
    group:
        token:
            - none
    user:
        token:
            - none

    # Администраторы бота. Будут доступны некоторые команды. ИДы писать только цифрами.
    admins:
        - 1

regexps:
    # Регулярные выражения для поиска упоминаний, ссылок, и т.д.
    links_pattern: (https?:\/\/)?(www\.)?vk\.com\/(([a-zA-Z0-9._])*)\/?
    hyperlinks_pattern: (\[((club|id)[\d+]{1,9})\|([^]]*)])
    invite_links_pattern: ((http://|https://)?(vk\.me)\/join/([a-zA-Z0-9_./=]+))
    shortened_links_patterns: ((http://|https://)?(vk\.cc)\/([a-zA-Z0-9_./=]+))


database:
    host: 127.0.0.1
    port: 3306
    user: admin
    password: admin

    database: none
    collection: none

    # Если установлен url, игнорируются параметры host, port, user, password
    url: none


triggers:
    mentions:
        user: false
        group: false
    attachments:
        photo: false
        audio: false
        video: false
        doc: false
        market: false
        article: false
        story: false
        graffiti: false
    invite_links: false
    short_links: false
    invites: false


middlewares:
    ignore_group_messages: true


logging:
    # Включить логирование всех уровней?
    log: false
    # Включить логирование отладочной информации?
    log_debug: false
    # Включить логирование всех ошибок?
    log_errors: false
    # Включить логирование в консоль?
    log_console: false

    # Путь записи логов всех уровней.
    log_path: logs/%Y-%m-%d_%H.log
    # Путь записи логов с ошибками.
    log_errors_path: logs/%Y-%m-%d_%H-error.log